### ISSUE TITLE
reason for which we don't make the top image width=100%?

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/browser-extension#30]
very often it seems to me that i look at an article in the reader and i wonder why is the top image sitting "shyly" in the corner as opposed to taking the full width of the column. screenshot of the latest article with which this happened:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/464519/198871421-042d2d08-b901-47fe-a717-8713f57615b2.png">

**Comment by Emmategl** [comment]
We set a max-height of 250px, because we felt it would "take over" the view, if the image took up a lot of space. If you have to scroll to see the first text. 

If we made this example full width, we would only see one line of text, when opening the reader. Though, maybe that is okay?
![Skærmbillede 2022-10-30 kl  11 24 33](https://user-images.githubusercontent.com/73998181/198873955-b205a6e1-9760-46f8-be68-ba219cffa5b5.png)

But we did see examples where images were tall and slim. And then you had to scroll to even see text - and full width would still not be the full width of the reader view. But maybe we don't see this so often, because we now uses the social media image - and this is likely often a format where width is bigger than height. 

So, if we change it, we should probably still set some max-height, so we avoid using full-width of very tall images.

**Comment by mircealungu** [comment]
I see the point of the image taking over the view. OTOH, people are used to this I think... In fact, we're actually doing better than the original article in the above example!!! We show the whole image and one line of text which is much more than they achieve :)

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/464519/198990890-eddd2bb1-b4a0-4d01-857c-edc76f536149.png">

I think a max-height for very tall images would probably be fine though.

**Comment by tfnribeiro** [comment]
This is done now in the reader in the Web and Extension. 

![image](https://github.com/user-attachments/assets/aef3dbca-8955-4559-b315-3b4c27ebb88a)

![image](https://github.com/user-attachments/assets/ab1a35cf-657b-4d13-b9a1-d270073ef5b1)
